spring:
  application:
    name: spring-ai-functionCall
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: gpt-4

weather:
  api:
    key: ${WEATHER_API}
    url: http://api.weatherapi.com/v1/current.json?key={key}&q={q}